### ISSUE TITLE
OS detection returns windows when on WSL Ubuntu

### ISSUE THREAD

**Issue by fletch3555** [orchestral/dusk-updater#5]
- Package Version: v1.2.1
- Laravel Dusk Version: v5.11.0
- PHP Version: 7.4.4

### Description:
`dusk-updater detect` is unable to find the chrome installation when on WSL since the OS detection identifies it as windows.  This is because $PHP_OS returns "win", which is more likely a php problem, but not one that's likely to be fixed anytime soon.

Additionally, I'm unable to simply pass in the path to the chrome installation because:
```
[InvalidArgumentException]
Chrome version cannot be detected in custom installation path on Windows.
```

### Steps To Reproduce:

1. Start with a Windows 10 machine with an ubuntu instance running in WSL, with `php` and `chromium-browser` installed
2. Setup a project that uses dusk-updater.
3. Run `./vendor/bin/dusk-updater detect --auto-update`

### Recommendation
Use `php_uname('s')` instead.  On WSL Ubuntu, it correctly returns "Linux".  Native windows returns "Windows NT".  I don't have a Mac to test, but I would expect "Darwin" (https://www.php.net/manual/en/function.php-uname.php)

**Comment by crynobone** [comment]
Can you try `v1.2.2`, which will check against `PHP_OS_FAMILY` if it is available.

**Comment by fletch3555** [comment]
Works perfectly! Thanks for the insanely fast response and resolution!
