### ISSUE TITLE
`Update` returns result in contradiction with `detect --auto-update` that fails

### ISSUE THREAD

**Issue by GeoSot** [orchestral/dusk-updater#7]
- Package Version: 7.7
- Laravel Dusk Version: 7.7
- PHP Version: 8.1

### Description:
When I run the two basic commands, I get the following result
![image](https://user-images.githubusercontent.com/22406063/188158755-41817d21-2100-4ae9-a606-a1e565f95679.png)

Is it normal to get results on `update` command and on `detect --auto-update` to get this exception and if I debug the process I get the errorOutput ` /usr/bin/google-chrome: not found`

![image](https://user-images.githubusercontent.com/22406063/188177553-c4a81f92-ce81-403e-a627-b9a5c83f27dc.png)

### Steps To Reproduce:

Just run on ubuntu 22 using Laravel sail (Laravel 9) the commands  `update` command and on `detect --auto-update`

**Comment by crynobone** [comment]
The update command would just pull in the latest version from repository, while detect would check the local installed version and only download the same version available.

**Comment by GeoSot** [comment]
And as the first one shows that downloaded the binary, shouldn't be normal for the second one, to find this binary file?

**Comment by crynobone** [comment]
If your Chrome/Chromium installed as version 94, and you loading ChromeDriver 104. It using a different API and may not work.

**Comment by GeoSot** [comment]
@crynobone Thank you for your help. 
Please, a last question. 

I found out that in contradiction that I run the `update` command through sail, the chromeDriver is detected only if I use the `detect` command locally and not through sail (not in docker). 
I something I miss here?

**Comment by crynobone** [comment]
It would happen when dusk-updater detect Chrome/Chromium installation on your local but not inside sail. Both are separate environment

**Comment by GeoSot** [comment]
I can understand this, but I cannot understand why it doesn't detect it in on sail. 
According to sail-dusk documentation, it doesn't need any special configuration

**Comment by crynobone** [comment]
> According to sail-dusk documentation, it doesn't need any special configuration

No idea. you can set `--chome-dir` option if it uses custom installed directory.

**Comment by GeoSot** [comment]
Thank you for your responses 🙂
